package by.htp.ex.controller;

public enum CommandName {
    GO_TO_MAIN_PAGE, GO_TO_NEWS, GO_TO_VIEW_NEWS,GO_TO_EDIT_NEWS, GO_TO_ADD_NEWS, GO_TO_404,
    DO_REGISTER, DO_SIGNIN, DO_SIGN_OUT, DO_EDIT_NEWS, DO_ADD_NEWS, DO_ADD_COMMENT, DO_DELETE_NEWS, DO_DELETE_COMMENT, DO_ADD_TRANSLATE,
    DO_ADD_LIKE,
    CHANGE_LOCAL;
}
